/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dd64dc47-e941-4f9e-9cdb-b453a942a3bb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TreaXS1gN",
    "aws_user_pools_web_client_id": "7ii3rmdc6g0522jmio7pl64g5i",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kcffhy76ovfodelkuyrzrgheli.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cn46lzcoyfd4nfjtumyve5g7ri",
    "aws_user_files_s3_bucket": "amplify-react-test200908-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
